///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep_ClinicManagement.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("b80d136a-8010-426d-b958-a5b527e8ee03", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep_ClinicManagement.SAFERsleep_ClinicManagementRepository repository.
        /// </summary>
        public static SAFERsleep_ClinicManagement.SAFERsleep_ClinicManagementRepository repo = SAFERsleep_ClinicManagement.SAFERsleep_ClinicManagementRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            varPassWord = "poi098)(*";
            varNHI = "PRE1002";
            varFirstName = "Preop1002";
            varLastName = "Preop1002";
            varSex = "Male";
            varSearchNHI = "PRE1003";
            varOperationName = "Operation1";
            varAppDate = "24/05/2018";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPassWord;

        /// <summary>
        /// Gets or sets the value of variable varPassWord.
        /// </summary>
        [TestVariable("34e53bf4-aab2-49c5-b691-f59dbde52613")]
        public string varPassWord
        {
            get { return _varPassWord; }
            set { _varPassWord = value; }
        }

        string _varNHI;

        /// <summary>
        /// Gets or sets the value of variable varNHI.
        /// </summary>
        [TestVariable("a3709b37-8f68-4cb4-8b0a-169c356e7c8d")]
        public string varNHI
        {
            get { return _varNHI; }
            set { _varNHI = value; }
        }

        string _varFirstName;

        /// <summary>
        /// Gets or sets the value of variable varFirstName.
        /// </summary>
        [TestVariable("71540618-1edd-4eb3-9212-ba187f76604c")]
        public string varFirstName
        {
            get { return _varFirstName; }
            set { _varFirstName = value; }
        }

        string _varLastName;

        /// <summary>
        /// Gets or sets the value of variable varLastName.
        /// </summary>
        [TestVariable("4affad6c-0cc4-4c92-8da0-8b9403f7211e")]
        public string varLastName
        {
            get { return _varLastName; }
            set { _varLastName = value; }
        }

        string _varSex;

        /// <summary>
        /// Gets or sets the value of variable varSex.
        /// </summary>
        [TestVariable("84593c5e-9672-4bc0-a958-1519deea2e68")]
        public string varSex
        {
            get { return _varSex; }
            set { _varSex = value; }
        }

        string _varSearchNHI;

        /// <summary>
        /// Gets or sets the value of variable varSearchNHI.
        /// </summary>
        [TestVariable("ffa558af-af13-4749-adc5-625a425d975a")]
        public string varSearchNHI
        {
            get { return _varSearchNHI; }
            set { _varSearchNHI = value; }
        }

        string _varOperationName;

        /// <summary>
        /// Gets or sets the value of variable varOperationName.
        /// </summary>
        [TestVariable("9e387255-3aec-4a0f-baf3-dbec98fccafb")]
        public string varOperationName
        {
            get { return _varOperationName; }
            set { _varOperationName = value; }
        }

        string _varAppDate;

        /// <summary>
        /// Gets or sets the value of variable varAppDate.
        /// </summary>
        [TestVariable("1ec29d4b-4024-4b7d-96f4-504071d76267")]
        public string varAppDate
        {
            get { return _varAppDate; }
            set { _varAppDate = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://testlab.safersleep.net/ClinicManagement/#/preop/appointment' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://testlab.safersleep.net/ClinicManagement/#/preop/appointment", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
