///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.ConfirmationFeatures.WebAirs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfirmWebAirs recording.
    /// </summary>
    [TestModule("6a71ca38-3531-4073-9f07-b536e1656b5a", ModuleType.Recording, 1)]
    public partial class ConfirmWebAirs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static ConfirmWebAirs instance = new ConfirmWebAirs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfirmWebAirs()
        {
            WebAirsConfirmBtn = "Yes";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfirmWebAirs Instance
        {
            get { return instance; }
        }

#region Variables

        string _WebAirsConfirmBtn;

        /// <summary>
        /// Gets or sets the value of variable WebAirsConfirmBtn.
        /// </summary>
        [TestVariable("7df8638f-6dd2-43c4-9698-456652483437")]
        public string WebAirsConfirmBtn
        {
            get { return _WebAirsConfirmBtn; }
            set { _WebAirsConfirmBtn = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmConfirmation.ReportToWebAIRSMessage'.", repo.FrmConfirmation.ReportToWebAIRSMessageInfo, new RecordItemIndex(0));
            Validate.Exists(repo.FrmConfirmation.ReportToWebAIRSMessageInfo);
            Delay.Milliseconds(0);
            
            ClickWebAirsButton(WebAirsConfirmBtn);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
