///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep_MedRec.Recordings.MedRecPostOp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetMedRevInterv recording.
    /// </summary>
    [TestModule("6591bd4b-dc7d-49a4-9e95-73d3b987d85a", ModuleType.Recording, 1)]
    public partial class SetMedRevInterv : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep_MedRec.SAFERsleep_MedRecRepository repository.
        /// </summary>
        public static SAFERsleep_MedRec.SAFERsleep_MedRecRepository repo = SAFERsleep_MedRec.SAFERsleep_MedRecRepository.Instance;

        static SetMedRevInterv instance = new SetMedRevInterv();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetMedRevInterv()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetMedRevInterv Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Button1.
        /// </summary>
        [TestVariable("2a0930d5-154c-40a3-b49f-617e682843f5")]
        public string Button1
        {
            get { return repo.Button1; }
            set { repo.Button1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Priority.
        /// </summary>
        [TestVariable("cf669a8b-11a5-404e-aa0a-d54875911a26")]
        public string Priority
        {
            get { return repo.Priority; }
            set { repo.Priority = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Button2.
        /// </summary>
        [TestVariable("840e3977-56f4-418f-a4b8-bfe0ee1f19b2")]
        public string Button2
        {
            get { return repo.Button2; }
            set { repo.Button2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Button3.
        /// </summary>
        [TestVariable("d564e9be-95df-4226-b700-b8b26472bf33")]
        public string Button3
        {
            get { return repo.Button3; }
            set { repo.Button3 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MedRecWindow.MedRec.MedReviewIntervention.Reason' at Center.", repo.MedRecWindow.MedRec.MedReviewIntervention.ReasonInfo, new RecordItemIndex(0));
            repo.MedRecWindow.MedRec.MedReviewIntervention.Reason.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MedRecWindow.MedRec.AddPatient.Priority' at Center.", repo.MedRecWindow.MedRec.AddPatient.PriorityInfo, new RecordItemIndex(1));
            repo.MedRecWindow.MedRec.AddPatient.Priority.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MedRecWindow.MedRec.MedReviewIntervention.Intervention' at Center.", repo.MedRecWindow.MedRec.MedReviewIntervention.InterventionInfo, new RecordItemIndex(2));
            repo.MedRecWindow.MedRec.MedReviewIntervention.Intervention.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MedRecWindow.MedRec.MedReviewIntervention.Outcomes' at Center.", repo.MedRecWindow.MedRec.MedReviewIntervention.OutcomesInfo, new RecordItemIndex(3));
            repo.MedRecWindow.MedRec.MedReviewIntervention.Outcomes.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MedRecWindow.MedRec.MedReviewIntervention.Save' at Center.", repo.MedRecWindow.MedRec.MedReviewIntervention.SaveInfo, new RecordItemIndex(4));
            repo.MedRecWindow.MedRec.MedReviewIntervention.Save.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
