///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.Drugs.FunctionalTestDrugs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickOnAddDrugButton recording.
    /// </summary>
    [TestModule("f6557c49-e029-4b89-bced-b51aefb798d2", ModuleType.Recording, 1)]
    public partial class ClickOnAddDrugButton : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static ClickOnAddDrugButton instance = new ClickOnAddDrugButton();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickOnAddDrugButton()
        {
            TimeAddDrug = "00:00";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickOnAddDrugButton Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable TimeAddDrug.
        /// </summary>
        [TestVariable("364ef050-0880-4b5d-95ab-715fce8eb2f8")]
        public string TimeAddDrug
        {
            get { return repo.TimeAddDrug; }
            set { repo.TimeAddDrug = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmORMain.OR_Modules.Drugs' at Center.", repo.FrmORMain.OR_Modules.DrugsInfo, new RecordItemIndex(0));
            repo.FrmORMain.OR_Modules.Drugs.Click();
            Delay.Milliseconds(200);
            
            // Click on Drug tab
            Report.Log(ReportLevel.Info, "Mouse", "Click on Drug tab\r\nMouse Left Click item 'FrmORMain.Drugs.Tabs.DrugsTab' at Center.", repo.FrmORMain.Drugs.Tabs.DrugsTabInfo, new RecordItemIndex(1));
            repo.FrmORMain.Drugs.Tabs.DrugsTab.Click();
            Delay.Milliseconds(200);
            
            // Click on Add Drug
            Report.Log(ReportLevel.Info, "Mouse", "Click on Add Drug\r\nMouse Left Click item 'FrmORMain.Drugs.Drugs.AddDrugF4' at Center.", repo.FrmORMain.Drugs.Drugs.AddDrugF4Info, new RecordItemIndex(2));
            repo.FrmORMain.Drugs.Drugs.AddDrugF4.Click();
            Delay.Milliseconds(200);
            
            // Save the time when add drug
            Report.Log(ReportLevel.Info, "Get Value", "Save the time when add drug\r\nGetting attribute 'Text' from item 'FrmEditDrug.DrugTime' and assigning its value to variable 'TimeAddDrug'.", repo.FrmEditDrug.DrugTimeInfo, new RecordItemIndex(3));
            TimeAddDrug = repo.FrmEditDrug.DrugTime.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
