///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERSleep_AP.Recordings.ActiveProblems
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyAddedConditions recording.
    /// </summary>
    [TestModule("41a54530-162d-4c9a-8d69-21fa0b24f2c3", ModuleType.Recording, 1)]
    public partial class VerifyAddedConditions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERSleep_AP.SAFERSleep_APRepository repository.
        /// </summary>
        public static SAFERSleep_AP.SAFERSleep_APRepository repo = SAFERSleep_AP.SAFERSleep_APRepository.Instance;

        static VerifyAddedConditions instance = new VerifyAddedConditions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyAddedConditions()
        {
            IsSelected = "Yes";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyAddedConditions Instance
        {
            get { return instance; }
        }

#region Variables

        string _IsSelected;

        /// <summary>
        /// Gets or sets the value of variable IsSelected.
        /// </summary>
        [TestVariable("8a6afd0a-8490-4971-907d-41a0d33ee114")]
        public string IsSelected
        {
            get { return _IsSelected; }
            set { _IsSelected = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ConditionDetail.
        /// </summary>
        [TestVariable("79c63260-e488-4215-a12e-69fec3dabad1")]
        public string ConditionDetail
        {
            get { return repo.ConditionDetail; }
            set { repo.ConditionDetail = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Condition.
        /// </summary>
        [TestVariable("b8617e85-cd60-4f02-8460-4d431a2baf66")]
        public string Condition
        {
            get { return repo.Condition; }
            set { repo.Condition = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            ValidateConditionExisted(IsSelected);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
