///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.Fluids.FunctionalTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickEditFluidInput recording.
    /// </summary>
    [TestModule("0f896747-8d7a-4048-b708-75e9b8ed1097", ModuleType.Recording, 1)]
    public partial class ClickEditFluidInput : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static ClickEditFluidInput instance = new ClickEditFluidInput();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickEditFluidInput()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickEditFluidInput Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable InputUnit.
        /// </summary>
        [TestVariable("f7ae56b5-4f13-4bca-9e52-cb482d8ef45c")]
        public string InputUnit
        {
            get { return repo.InputUnit; }
            set { repo.InputUnit = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable StartInputLevel.
        /// </summary>
        [TestVariable("f7d2923b-5e58-46ad-bc1e-8e36673a7b21")]
        public string StartInputLevel
        {
            get { return repo.StartInputLevel; }
            set { repo.StartInputLevel = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable FluidInputName.
        /// </summary>
        [TestVariable("85b9105e-a9b6-4a9c-be8e-99aed3840454")]
        public string FluidInputName
        {
            get { return repo.FluidInputName; }
            set { repo.FluidInputName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmORMain.FluidBalance.Tabs.FluidInput' at Center.", repo.FrmORMain.FluidBalance.Tabs.FluidInputInfo, new RecordItemIndex(0));
            repo.FrmORMain.FluidBalance.Tabs.FluidInput.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmORMain.FluidBalance.AddedFluidInput' at Center.", repo.FrmORMain.FluidBalance.AddedFluidInputInfo, new RecordItemIndex(1));
            repo.FrmORMain.FluidBalance.AddedFluidInput.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmORMain.FluidBalance.EditFluidInput' at Center.", repo.FrmORMain.FluidBalance.EditFluidInputInfo, new RecordItemIndex(2));
            repo.FrmORMain.FluidBalance.EditFluidInput.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
