///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.Main_Menu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenNewAnaesthetic_NewPatient recording.
    /// </summary>
    [TestModule("c31ae451-916b-459a-a511-b8aa58d80a3b", ModuleType.Recording, 1)]
    public partial class OpenNewAnaesthetic_NewPatient : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static OpenNewAnaesthetic_NewPatient instance = new OpenNewAnaesthetic_NewPatient();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenNewAnaesthetic_NewPatient()
        {
            PatientNumber = "FWU5011";
            LastName = "Test";
            FirstNames = "Patient";
            DOB = "3/8/2012";
            Sex = "Female";
            IsPaed = "false";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenNewAnaesthetic_NewPatient Instance
        {
            get { return instance; }
        }

#region Variables

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("e456ca06-5f92-4ccf-b6be-9534e4e2adb9")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        string _FirstNames;

        /// <summary>
        /// Gets or sets the value of variable FirstNames.
        /// </summary>
        [TestVariable("0150f131-2457-4f9b-a159-5886706a4209")]
        public string FirstNames
        {
            get { return _FirstNames; }
            set { _FirstNames = value; }
        }

        string _DOB;

        /// <summary>
        /// Gets or sets the value of variable DOB.
        /// </summary>
        [TestVariable("7a0ef193-4d9b-4227-a32b-54086084d085")]
        public string DOB
        {
            get { return _DOB; }
            set { _DOB = value; }
        }

        string _Sex;

        /// <summary>
        /// Gets or sets the value of variable Sex.
        /// </summary>
        [TestVariable("661d488e-428e-47f6-bbd5-8bbe7b564cb8")]
        public string Sex
        {
            get { return _Sex; }
            set { _Sex = value; }
        }

        string _IsPaed;

        /// <summary>
        /// Gets or sets the value of variable IsPaed.
        /// </summary>
        [TestVariable("a72aab4e-8dab-4d99-92e9-b932838fa6c0")]
        public string IsPaed
        {
            get { return _IsPaed; }
            set { _IsPaed = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PatientNumber.
        /// </summary>
        [TestVariable("3bf1dba6-2bfd-479b-852b-33d37ef0ca43")]
        public string PatientNumber
        {
            get { return repo.PatientNumber; }
            set { repo.PatientNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMainMenu.NewAnaesthetic' at Center.", repo.FrmMainMenu.NewAnaestheticInfo, new RecordItemIndex(0));
            repo.FrmMainMenu.NewAnaesthetic.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PatientNumber' with focus on 'FrmNewAnaesthetic.PatientNumber'.", repo.FrmNewAnaesthetic.PatientNumberInfo, new RecordItemIndex(1));
            repo.FrmNewAnaesthetic.PatientNumber.PressKeys(PatientNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmNewAnaesthetic.OK' at Center.", repo.FrmNewAnaesthetic.OKInfo, new RecordItemIndex(2));
            repo.FrmNewAnaesthetic.OK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmConfirmation.Yes' at Center.", repo.FrmConfirmation.YesInfo, new RecordItemIndex(3));
            repo.FrmConfirmation.Yes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'FrmUpdatePatientDetails.LastName'.", repo.FrmUpdatePatientDetails.LastNameInfo, new RecordItemIndex(4));
            repo.FrmUpdatePatientDetails.LastName.PressKeys(LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstNames' with focus on 'FrmUpdatePatientDetails.FirstNames'.", repo.FrmUpdatePatientDetails.FirstNamesInfo, new RecordItemIndex(5));
            repo.FrmUpdatePatientDetails.FirstNames.PressKeys(FirstNames);
            Delay.Milliseconds(0);
            
            Enter_DOB(repo.FrmUpdatePatientDetails.DOBInfo, IsPaed);
            Delay.Milliseconds(0);
            
            SelectSex(Sex);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmUpdatePatientDetails.OK' at Center.", repo.FrmUpdatePatientDetails.OKInfo, new RecordItemIndex(8));
            repo.FrmUpdatePatientDetails.OK.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
