///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.PainPrescriptions.Infusion2Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateRate2 recording.
    /// </summary>
    [TestModule("ac9bdc1e-709c-40c8-ad27-01ed4cb08a11", ModuleType.Recording, 1)]
    public partial class ValidateRate2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static ValidateRate2 instance = new ValidateRate2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateRate2()
        {
            PrescriptionType = "Epidural Analgesia";
            PrescriptionDetails = "";
            PrescriptionUnit = "ml";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateRate2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _PrescriptionUnit;

        /// <summary>
        /// Gets or sets the value of variable PrescriptionUnit.
        /// </summary>
        [TestVariable("c292b420-d939-49d6-b974-d257f22cd12c")]
        public string PrescriptionUnit
        {
            get { return _PrescriptionUnit; }
            set { _PrescriptionUnit = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PrescriptionType.
        /// </summary>
        [TestVariable("1c0470b2-85ce-4b35-b35d-e0ff202e3363")]
        public string PrescriptionType
        {
            get { return repo.PrescriptionType; }
            set { repo.PrescriptionType = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PrescriptionDetails.
        /// </summary>
        [TestVariable("043eb59b-6b6b-4fae-8ae1-29ba0cd98572")]
        public string PrescriptionDetails
        {
            get { return repo.PrescriptionDetails; }
            set { repo.PrescriptionDetails = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CheckRate(PrescriptionDetails, PrescriptionUnit);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
