///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.Templates
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PACU_Save_Template recording.
    /// </summary>
    [TestModule("7ac5fde7-90cc-4483-9557-7ca51e340e66", ModuleType.Recording, 1)]
    public partial class PACU_Save_Template : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static PACU_Save_Template instance = new PACU_Save_Template();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PACU_Save_Template()
        {
            TemplateName = "Auto PACU";
            OxygenRate = "4";
            OxygenMask = "Hudson Mask";
            OxygenComment = "";
            OtherInstructions = "testing only";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PACU_Save_Template Instance
        {
            get { return instance; }
        }

#region Variables

        string _OxygenRate;

        /// <summary>
        /// Gets or sets the value of variable OxygenRate.
        /// </summary>
        [TestVariable("c4f92cc9-0a3e-46fd-a51c-eaba9df85536")]
        public string OxygenRate
        {
            get { return _OxygenRate; }
            set { _OxygenRate = value; }
        }

        string _OxygenMask;

        /// <summary>
        /// Gets or sets the value of variable OxygenMask.
        /// </summary>
        [TestVariable("37ff1128-a669-45cf-9ade-4a0bfe2cdf03")]
        public string OxygenMask
        {
            get { return _OxygenMask; }
            set { _OxygenMask = value; }
        }

        string _OxygenComment;

        /// <summary>
        /// Gets or sets the value of variable OxygenComment.
        /// </summary>
        [TestVariable("937e1eb6-a10b-4917-8145-8311bbca39bf")]
        public string OxygenComment
        {
            get { return _OxygenComment; }
            set { _OxygenComment = value; }
        }

        string _OtherInstructions;

        /// <summary>
        /// Gets or sets the value of variable OtherInstructions.
        /// </summary>
        [TestVariable("f95c605b-5bc7-4409-89a4-1bba00be2604")]
        public string OtherInstructions
        {
            get { return _OtherInstructions; }
            set { _OtherInstructions = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TemplateName.
        /// </summary>
        [TestVariable("4bc3f99a-9fbf-450f-8d4f-46d68bbadc65")]
        public string TemplateName
        {
            get { return repo.TemplateName; }
            set { repo.TemplateName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PACUFrequencyTime.
        /// </summary>
        [TestVariable("90fcabdd-ce6d-4b97-8bd2-f368b37a3541")]
        public string PACUFrequencyTime
        {
            get { return repo.PACUFrequencyTime; }
            set { repo.PACUFrequencyTime = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PACURoute.
        /// </summary>
        [TestVariable("63fcf69e-b0d9-476d-b928-7b3fa32c5ef1")]
        public string PACURoute
        {
            get { return repo.PACURoute; }
            set { repo.PACURoute = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PACUUnit.
        /// </summary>
        [TestVariable("4f8923b6-e637-47ba-aceb-6803319fe3fc")]
        public string PACUUnit
        {
            get { return repo.PACUUnit; }
            set { repo.PACUUnit = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PACUDose.
        /// </summary>
        [TestVariable("9eb83827-cf54-4080-b2d1-a15601671625")]
        public string PACUDose
        {
            get { return repo.PACUDose; }
            set { repo.PACUDose = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PACUDrug.
        /// </summary>
        [TestVariable("4e1270ec-2384-4f75-b680-0af588f1dff6")]
        public string PACUDrug
        {
            get { return repo.PACUDrug; }
            set { repo.PACUDrug = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmORMain.Templates' at Center.", repo.FrmORMain.TemplatesInfo, new RecordItemIndex(0));
            repo.FrmORMain.Templates.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Templates.TemplatesForm.SaveCurrentScreenAsTemplate' at Center.", repo.Templates.TemplatesForm.SaveCurrentScreenAsTemplateInfo, new RecordItemIndex(1));
            repo.Templates.TemplatesForm.SaveCurrentScreenAsTemplate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Back' Press.", new RecordItemIndex(2));
            Keyboard.Press(System.Windows.Forms.Keys.Back, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveTemplate.TemplateName' at Center.", repo.SaveTemplate.TemplateNameInfo, new RecordItemIndex(3));
            repo.SaveTemplate.TemplateName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TemplateName'.", new RecordItemIndex(4));
            Keyboard.Press(TemplateName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(5));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveTemplate.ButtonOK' at Center.", repo.SaveTemplate.ButtonOKInfo, new RecordItemIndex(6));
            repo.SaveTemplate.ButtonOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Templates.TemplatesForm.TemplateListItem' at Center.", repo.Templates.TemplatesForm.TemplateListItemInfo, new RecordItemIndex(7));
            repo.Templates.TemplatesForm.TemplateListItem.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Templates.TemplatesForm.ViewTemplate' at Center.", repo.Templates.TemplatesForm.ViewTemplateInfo, new RecordItemIndex(8));
            repo.Templates.TemplatesForm.ViewTemplate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$OxygenRate) on item 'TemplateAdministration.PACU.PACUOxygenRate'.", repo.TemplateAdministration.PACU.PACUOxygenRateInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TemplateAdministration.PACU.PACUOxygenRateInfo, "Text", OxygenRate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$OxygenMask) on item 'TemplateAdministration.PACU.PACUOxygenMask'.", repo.TemplateAdministration.PACU.PACUOxygenMaskInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.TemplateAdministration.PACU.PACUOxygenMaskInfo, "Text", OxygenMask);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$OxygenComment) on item 'TemplateAdministration.PACU.PACUOxygenComment'.", repo.TemplateAdministration.PACU.PACUOxygenCommentInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.TemplateAdministration.PACU.PACUOxygenCommentInfo, "Text", OxygenComment);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$OtherInstructions) on item 'TemplateAdministration.PACU.PACUOtherInstructions'.", repo.TemplateAdministration.PACU.PACUOtherInstructionsInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.TemplateAdministration.PACU.PACUOtherInstructionsInfo, "Text", OtherInstructions);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TemplateAdministration.PACU.PACUListItem'.", repo.TemplateAdministration.PACU.PACUListItemInfo, new RecordItemIndex(13));
            Validate.Exists(repo.TemplateAdministration.PACU.PACUListItemInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TemplateAdministration.ButtonClose' at Center.", repo.TemplateAdministration.ButtonCloseInfo, new RecordItemIndex(14));
            repo.TemplateAdministration.ButtonClose.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Templates.TemplatesForm.Close' at Center.", repo.Templates.TemplatesForm.CloseInfo, new RecordItemIndex(15));
            repo.Templates.TemplatesForm.Close.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
