///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.ConfirmationFeatures.OperationDetails
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterOperationDetails recording.
    /// </summary>
    [TestModule("edb66074-601d-4ee5-9029-1bd33334fb77", ModuleType.Recording, 1)]
    public partial class EnterOperationDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static EnterOperationDetails instance = new EnterOperationDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterOperationDetails()
        {
            OperationDetails = "Test Operation";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterOperationDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _OperationDetails;

        /// <summary>
        /// Gets or sets the value of variable OperationDetails.
        /// </summary>
        [TestVariable("8683b05b-e80f-47d0-a688-a7310fd638eb")]
        public string OperationDetails
        {
            get { return _OperationDetails; }
            set { _OperationDetails = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PleaseEnterOperationDetails.OperationDetailsMessage'.", repo.PleaseEnterOperationDetails.OperationDetailsMessageInfo, new RecordItemIndex(0));
            Validate.Exists(repo.PleaseEnterOperationDetails.OperationDetailsMessageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PleaseEnterOperationDetails.OperationTextbox' at Center.", repo.PleaseEnterOperationDetails.OperationTextboxInfo, new RecordItemIndex(1));
            repo.PleaseEnterOperationDetails.OperationTextbox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$OperationDetails'.", new RecordItemIndex(2));
            Keyboard.Press(OperationDetails);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PleaseEnterOperationDetails.ButtonOK' at Center.", repo.PleaseEnterOperationDetails.ButtonOKInfo, new RecordItemIndex(4));
            repo.PleaseEnterOperationDetails.ButtonOK.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
