///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep_MedRec.Recordings.AutoUpdate
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BrowsePortalDL recording.
    /// </summary>
    [TestModule("3b030522-76c3-4c2d-b9e4-ebc8e27a8eb9", ModuleType.Recording, 1)]
    public partial class BrowsePortalDL : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep_MedRec.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep_MedRec.SAFERsleepORRepository repo = SAFERsleep_MedRec.SAFERsleepORRepository.Instance;

        static BrowsePortalDL instance = new BrowsePortalDL();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BrowsePortalDL()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BrowsePortalDL Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Server.
        /// </summary>
        [TestVariable("419dd702-9556-4f74-826c-b62d0c92b0e4")]
        public string Server
        {
            get { return repo.Server; }
            set { repo.Server = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://ATServer12R2.safersleep.net/portal/download' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://ATServer12R2.safersleep.net/portal/download", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SAFERsleepPortal.SAFERsleepMedRecClientLauncher'.", repo.SAFERsleepPortal.SAFERsleepMedRecClientLauncherInfo, new RecordItemIndex(2));
            Validate.Exists(repo.SAFERsleepPortal.SAFERsleepMedRecClientLauncherInfo);
            Delay.Milliseconds(0);
            
            ClosePortalDL();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
