///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SAFERsleep.Recordings.Post_Op_Medications
{
    public partial class EnterPostOpInformation
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_ButtonYes()
        {
        	var YesButton = repo.FrmORMain.PostOpMedication.Information.ButtonYes;
        	
        	if (YesButton.Pressed)
        		System.Diagnostics.Debug.WriteLine("VTE button is already pressed");
        	else
        		YesButton.Click();
        }

        public void Key_sequence_VTEPrescribed(RepoItemInfo textInfo)
        {
        	if (repo.FrmORMain.PostOpMedication.Information.VTEPrescribed.TextValue == null)
        	{
	            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$VTEPrescribed' with focus on 'textInfo'.", textInfo);
	            textInfo.FindAdapter<Text>().PressKeys(VTEPrescribed);
        	}
        	else
        		System.Diagnostics.Debug.WriteLine("VTE prescription already set");
        }

    }
}
