///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.PainPrescriptions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetOxygenTherapy recording.
    /// </summary>
    [TestModule("5e617624-78cc-4ca8-8cc7-78a239103650", ModuleType.Recording, 1)]
    public partial class SetOxygenTherapy : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static SetOxygenTherapy instance = new SetOxygenTherapy();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetOxygenTherapy()
        {
            OxygenTherapy = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetOxygenTherapy Instance
        {
            get { return instance; }
        }

#region Variables

        string _OxygenTherapy;

        /// <summary>
        /// Gets or sets the value of variable OxygenTherapy.
        /// </summary>
        [TestVariable("91bddf3b-d7e3-4c60-a518-3cd33b72f6e9")]
        public string OxygenTherapy
        {
            get { return _OxygenTherapy; }
            set { _OxygenTherapy = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollection_OR.Clear_TextBox(repo.FrmORMain.PainPrescriptions.PainPrescriptionOxygenScriptInfo, "Combobox");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$OxygenTherapy'.", new RecordItemIndex(1));
            Keyboard.Press(OxygenTherapy);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(2));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$OxygenTherapy) on item 'FrmORMain.PainPrescriptions.PainPrescriptionOxygenScript'.", repo.FrmORMain.PainPrescriptions.PainPrescriptionOxygenScriptInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.FrmORMain.PainPrescriptions.PainPrescriptionOxygenScriptInfo, "Text", OxygenTherapy);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
