///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.Patient_Details.Clinical_Team
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectSurgeon_1 recording.
    /// </summary>
    [TestModule("e34a05a2-9142-4df0-b1c7-5aad5f49fde2", ModuleType.Recording, 1)]
    public partial class SelectSurgeon_1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static SelectSurgeon_1 instance = new SelectSurgeon_1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectSurgeon_1()
        {
            Surgeon_1 = "Evans, Kay";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectSurgeon_1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Surgeon_1;

        /// <summary>
        /// Gets or sets the value of variable Surgeon_1.
        /// </summary>
        [TestVariable("28387f80-2039-4638-afa2-b2677eda609e")]
        public string Surgeon_1
        {
            get { return _Surgeon_1; }
            set { _Surgeon_1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Surgeon_1' with focus on 'FrmORMain.Patient_Details.Clinical_Team.Surgeon1'.", repo.FrmORMain.Patient_Details.Clinical_Team.Surgeon1Info, new RecordItemIndex(0));
            repo.FrmORMain.Patient_Details.Clinical_Team.Surgeon1.PressKeys(Surgeon_1);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(1));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
