///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.Fluids.FunctionalTesting.Output
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterOutput_DateAndTime recording.
    /// </summary>
    [TestModule("0278e773-5cea-4907-ab28-13f4e563f161", ModuleType.Recording, 1)]
    public partial class EnterOutput_DateAndTime : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static EnterOutput_DateAndTime instance = new EnterOutput_DateAndTime();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterOutput_DateAndTime()
        {
            NewDate = "6/02/2019";
            NewTime = "14:14";
            TimeAddFluid = "14:00";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterOutput_DateAndTime Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewDate;

        /// <summary>
        /// Gets or sets the value of variable NewDate.
        /// </summary>
        [TestVariable("02fc4649-c68c-44dd-99e4-c2cb516e2010")]
        public string NewDate
        {
            get { return _NewDate; }
            set { _NewDate = value; }
        }

        string _NewTime;

        /// <summary>
        /// Gets or sets the value of variable NewTime.
        /// </summary>
        [TestVariable("ab7c66a6-c34c-471b-8f89-08691d727e08")]
        public string NewTime
        {
            get { return _NewTime; }
            set { _NewTime = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TimeAddFluid.
        /// </summary>
        [TestVariable("55b471f1-48d9-4d9b-87e1-bf9d27adf283")]
        public string TimeAddFluid
        {
            get { return repo.TimeAddFluid; }
            set { repo.TimeAddFluid = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //UserCodeCollection_OR.Clear_TextBox(repo.AddFluidOutput.DateInfo, "Text");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewDate'.", new RecordItemIndex(1));
            //Keyboard.Press(NewDate);
            //Delay.Milliseconds(100);
            
            UserCodeCollection_OR.Clear_TextBox(repo.AddFluidOutput.TimeInfo, "Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NewTime'.", new RecordItemIndex(3));
            Keyboard.Press(NewTime);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'AddFluidOutput.Time' and assigning its value to variable 'TimeAddFluid'.", repo.AddFluidOutput.TimeInfo, new RecordItemIndex(4));
            TimeAddFluid = repo.AddFluidOutput.Time.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
