///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep.Recordings.AutoUpdate
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenORLauncher recording.
    /// </summary>
    [TestModule("0a3f4e1c-cb0b-4877-8015-51d8739880b5", ModuleType.Recording, 1)]
    public partial class OpenORLauncher : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep.SAFERsleepORRepository repository.
        /// </summary>
        public static SAFERsleep.SAFERsleepORRepository repo = SAFERsleep.SAFERsleepORRepository.Instance;

        static OpenORLauncher instance = new OpenORLauncher();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenORLauncher()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenORLauncher Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Desktop.SAFERsleepORClientLauncher' at Center.", repo.Desktop.SAFERsleepORClientLauncherInfo, new RecordItemIndex(0));
            repo.Desktop.SAFERsleepORClientLauncher.DoubleClick();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Taskbar.SAFERsleepORClientLauncher' at Center.", repo.Taskbar.SAFERsleepORClientLauncherInfo, new RecordItemIndex(1));
            //repo.Taskbar.SAFERsleepORClientLauncher.Click();
            //Delay.Milliseconds(200);
            
            Mouse_Click_ButtonRun(repo.OpenFileSecurityWarning.ButtonRunInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaferSleepClientApplicationUpdateCore.Yes' at Center.", repo.SaferSleepClientApplicationUpdateCore.YesInfo, new RecordItemIndex(3));
            repo.SaferSleepClientApplicationUpdateCore.Yes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5m.", new RecordItemIndex(4));
            Delay.Duration(300000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
