///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep_Portal.Recordings.Forms.PreOp_Assessment.Medical_Surgical_History
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Fill_Habits recording.
    /// </summary>
    [TestModule("b7aaf8de-785b-4f3b-8400-b9c0ee32521b", ModuleType.Recording, 1)]
    public partial class Fill_Habits : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep_Portal.SAFERsleep_PortalRepository repository.
        /// </summary>
        public static SAFERsleep_Portal.SAFERsleep_PortalRepository repo = SAFERsleep_Portal.SAFERsleep_PortalRepository.Instance;

        static Fill_Habits instance = new Fill_Habits();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Fill_Habits()
        {
            DoYouSmoke_Status = "Non-smoker";
            DrinkAlcohol_Status = "Yes";
            DrinkAlcohol_Units = "5";
            DrinkAlcohol_Note = "this is a test note";
            OtherDependencies_Status = "Yes";
            OtherDependencies_Note = "this is a test note";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Fill_Habits Instance
        {
            get { return instance; }
        }

#region Variables

        string _DoYouSmoke_Status;

        /// <summary>
        /// Gets or sets the value of variable DoYouSmoke_Status.
        /// </summary>
        [TestVariable("e44edf83-31fe-4b73-b06a-d34bec84849d")]
        public string DoYouSmoke_Status
        {
            get { return _DoYouSmoke_Status; }
            set { _DoYouSmoke_Status = value; }
        }

        string _DrinkAlcohol_Status;

        /// <summary>
        /// Gets or sets the value of variable DrinkAlcohol_Status.
        /// </summary>
        [TestVariable("6bb56461-9e50-4b5b-9ea9-cc3192561692")]
        public string DrinkAlcohol_Status
        {
            get { return _DrinkAlcohol_Status; }
            set { _DrinkAlcohol_Status = value; }
        }

        string _DrinkAlcohol_Units;

        /// <summary>
        /// Gets or sets the value of variable DrinkAlcohol_Units.
        /// </summary>
        [TestVariable("b315768a-c69a-46e2-960d-13d8dfbefa13")]
        public string DrinkAlcohol_Units
        {
            get { return _DrinkAlcohol_Units; }
            set { _DrinkAlcohol_Units = value; }
        }

        string _DrinkAlcohol_Note;

        /// <summary>
        /// Gets or sets the value of variable DrinkAlcohol_Note.
        /// </summary>
        [TestVariable("c266430a-3b93-4a1d-824b-2d77f255fac6")]
        public string DrinkAlcohol_Note
        {
            get { return _DrinkAlcohol_Note; }
            set { _DrinkAlcohol_Note = value; }
        }

        string _OtherDependencies_Status;

        /// <summary>
        /// Gets or sets the value of variable OtherDependencies_Status.
        /// </summary>
        [TestVariable("0e205e1c-53fd-4a56-9db7-d993c77582b3")]
        public string OtherDependencies_Status
        {
            get { return _OtherDependencies_Status; }
            set { _OtherDependencies_Status = value; }
        }

        string _OtherDependencies_Note;

        /// <summary>
        /// Gets or sets the value of variable OtherDependencies_Note.
        /// </summary>
        [TestVariable("438a847e-e380-441b-988a-83a6ec547317")]
        public string OtherDependencies_Note
        {
            get { return _OtherDependencies_Note; }
            set { _OtherDependencies_Note = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PreOperativeForm.PreOpAssessment_Form.MedicalSurgicalHistorySection.Habits_Tab' at Center.", repo.PreOperativeForm.PreOpAssessment_Form.MedicalSurgicalHistorySection.Habits_TabInfo, new RecordItemIndex(0));
            repo.PreOperativeForm.PreOpAssessment_Form.MedicalSurgicalHistorySection.Habits_Tab.Click();
            
            Set_DoYouSmoke(DoYouSmoke_Status);
            
            Set_DrinkAlcohol(DrinkAlcohol_Status, ValueConverter.ArgumentFromString<int>("units", DrinkAlcohol_Units), DrinkAlcohol_Note);
            
            Set_OtherDependencies(OtherDependencies_Status, OtherDependencies_Note);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
