///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SAFERsleep_Portal.Recordings.Forms.PreOp_Assessment.Medical_Surgical_History
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Set_PreviousAnaesthetics recording.
    /// </summary>
    [TestModule("0ec2001b-046e-456e-b43b-d1d13d217b06", ModuleType.Recording, 1)]
    public partial class Set_PreviousAnaesthetics : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SAFERsleep_Portal.SAFERsleep_PortalRepository repository.
        /// </summary>
        public static SAFERsleep_Portal.SAFERsleep_PortalRepository repo = SAFERsleep_Portal.SAFERsleep_PortalRepository.Instance;

        static Set_PreviousAnaesthetics instance = new Set_PreviousAnaesthetics();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Set_PreviousAnaesthetics()
        {
            PreviousAnaesthetic_Status = "Yes";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Set_PreviousAnaesthetics Instance
        {
            get { return instance; }
        }

#region Variables

        string _PreviousAnaesthetic_Status;

        /// <summary>
        /// Gets or sets the value of variable PreviousAnaesthetic_Status.
        /// </summary>
        [TestVariable("a5423eab-7904-4ac1-8e99-f26b6f5a43cd")]
        public string PreviousAnaesthetic_Status
        {
            get { return _PreviousAnaesthetic_Status; }
            set { _PreviousAnaesthetic_Status = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Set_PreviousAnaesthetic_Method(PreviousAnaesthetic_Status);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
